name: Hello-Jenkins

on: 
  workflow_dispatch:
    inputs:
      USERNAME:                      # Task 6.2: Add String parameter
        description: 'Enter Username'
        required: true
        default: 'Sivanesh'
        type: string

jobs:
  parameter-task:
    runs-on: ubuntu-latest
    steps:
      - name: Print Parameter Value
        run: echo "The username is ${{ github.event.inputs.USERNAME }}"
