name: Hello-Jenkins

on: 
  workflow_dispatch: # This enables the "Run workflow" button

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Verify Files
        run: ls -R
